[package]
name = "git_submodules"
version = "0.1.0"
authors = ["Steven Knight <steven@knight.c>"]

[dependencies]
git2 = "*"
serde = "1.0.57"
serde_json = "1.0.17"
serde_derive = "1.0.57"
clap = "2.31.2"
regex = "1.0.0"
flexi_logger = "0.8.3"
log = "0.4"
